import {
  Product,
  Course,
  PYQItem,
  ExamUpdate,
  ImportantDateItem,
  CurrentAffairItem,
  BlogPost,
  ExamCategory,
} from './types';

export const EXAM_CATEGORIES_DATA: {
  id: ExamCategory;
  name: { mr: string; en: string; hi: string };
  desc: { mr: string; en: string; hi: string };
  resourcesCount: number;
  iconName: string;
  badge?: string;
}[] = [
  {
    id: 'MPSC',
    name: { mr: 'MPSC राज्यसेवा', en: 'MPSC Rajyaseva', hi: 'MPSC राज्यसेवा' },
    desc: {
      mr: 'राज्यसेवा प्रिलिम्स व मेन्ससाठी सर्वंकष नोट्स, PYQs आणि चालू घडामोडी',
      en: 'Comprehensive notes, PYQs and current affairs for Prelims & Mains',
      hi: 'राज्यसेवा प्रीलिम्स और मेन्स के लिए संपूर्ण नोट्स, PYQs एवं करंट अफेयर्स',
    },
    resourcesCount: 142,
    iconName: 'GraduationCap',
    badge: 'Popular',
  },
  {
    id: 'PSI',
    name: { mr: 'PSI (पोलीस उपनिरीक्षक)', en: 'PSI (Sub Inspector)', hi: 'PSI (उपनिरीक्षक)' },
    desc: {
      mr: 'कायदा, राज्यघटना, इतिहास व भूगोल विशेष रिव्हिजन चार्ट्स',
      en: 'Law, Constitution, History & Geography revision charts',
      hi: 'विधि, संविधान, इतिहास एवं भूगोल विशेष रिवीजन चार्ट्स',
    },
    resourcesCount: 88,
    iconName: 'Shield',
    badge: 'Trending',
  },
  {
    id: 'STI',
    name: { mr: 'STI (राज्य कर निरीक्षक)', en: 'STI (State Tax Inspector)', hi: 'STI (राज्य कर निरीक्षक)' },
    desc: {
      mr: 'अर्थव्यवस्था, GST, चालू घडामोडी व ग्रुप B विशेष साहित्य',
      en: 'Economics, GST, Current Affairs & Group B dedicated material',
      hi: 'अर्थव्यवस्था, GST, समसामयिकी एवं ग्रुप B विशेष सामग्री',
    },
    resourcesCount: 76,
    iconName: 'Coins',
  },
  {
    id: 'ASO',
    name: { mr: 'ASO (मंत्रालय सहाय्यक)', en: 'ASO (Section Officer)', hi: 'ASO (अनुभाग अधिकारी)' },
    desc: {
      mr: 'भारतीय राज्यघटना, पंचायतराज आणि सामान्य अध्ययन क्विक नोट्स',
      en: 'Indian Constitution, Panchayati Raj and General Studies quick notes',
      hi: 'भारतीय संविधान, पंचायती राज एवं सामान्य अध्ययन क्विक नोट्स',
    },
    resourcesCount: 71,
    iconName: 'Building2',
  },
  {
    id: 'Talathi',
    name: { mr: 'तलाठी भरती (TCS/IBPS)', en: 'Talathi Bharti (TCS/IBPS)', hi: 'तलाठी भर्ती (TCS/IBPS)' },
    desc: {
      mr: 'मराठी व्याकरण, इंग्रजी, अंकगणित व बुद्धिमत्ता पॅटर्न-बेस्ड प्रश्नसंच',
      en: 'Marathi Grammar, English, Aptitude & Reasoning pattern question banks',
      hi: 'मराठी व्याकरण, अंग्रेजी, अंकगणित एवं रीजनिंग पैटर्न प्रश्न बैंक',
    },
    resourcesCount: 115,
    iconName: 'FileSpreadsheet',
    badge: 'High Demand',
  },
  {
    id: 'Police Bharti',
    name: { mr: 'महाराष्ट्र पोलीस भरती', en: 'Maharashtra Police Bharti', hi: 'महाराष्ट्र पुलिस भर्ती' },
    desc: {
      mr: 'सामान्य ज्ञान, चालू घडामोडी आणि ५०००+ सराव प्रश्नसंच ई-बुक्स',
      en: 'General Knowledge, Current Affairs and 5000+ practice question ebooks',
      hi: 'सामान्य ज्ञान, करंट अफेयर्स और 5000+ अभ्यास प्रश्न ई-बुक्स',
    },
    resourcesCount: 94,
    iconName: 'Award',
  },
  {
    id: 'Arogya Bharti',
    name: { mr: 'आरोग्य भरती व जिल्हा परिषद', en: 'Arogya Bharti & ZP', hi: 'आरोग्य भर्ती एवं ZP' },
    desc: {
      mr: 'आरोग्य सेवक, परिचारिका, औषध निर्माण अधिकारी व ZP तांत्रिक नोट्स',
      en: 'Arogya Sevak, ANM/GNM, Pharmacist and ZP technical study notes',
      hi: 'आरोग्य सेवक, फार्मासिस्ट एवं जिला परिषद तकनीकी नोट्स',
    },
    resourcesCount: 88,
    iconName: 'Award',
  },
  {
    id: 'TET / TAIT',
    name: { mr: 'TET / TAIT शिक्षक भरती', en: 'TET / TAIT Teacher Exam', hi: 'TET / TAIT शिक्षक भर्ती' },
    desc: {
      mr: 'बालमानसशास्त्र, अध्यापनशास्त्र आणि विषयवार वस्तुनिष्ठ नोट्स',
      en: 'Child Psychology, Pedagogy and subject-wise objective notes',
      hi: 'बाल मनोविज्ञान, शिक्षण शास्त्र एवं विषयवार वस्तुनिष्ठ नोट्स',
    },
    resourcesCount: 52,
    iconName: 'Sparkles',
  },
  {
    id: 'सरळसेवा',
    name: { mr: 'सरळसेवा व जिल्हा परिषद', en: 'Saralseva & ZP Bharti', hi: 'सरलसेवा एवं ZP भर्ती' },
    desc: {
      mr: 'ग्रामसेवक, आरोग्य सेवक व लिपिक पदांसाठी तांत्रिक व अतांत्रिक नोट्स',
      en: 'Technical and non-technical notes for Gramsevak, Arogya Sevak & Clerk',
      hi: 'ग्रामसेवक, आरोग्य सेवक एवं लिपिक पदों के लिए अध्ययन नोट्स',
    },
    resourcesCount: 82,
    iconName: 'Layers',
  },
  {
    id: 'Forest Service',
    name: { mr: 'महाराष्ट्र वनसेवा', en: 'Maharashtra Forest Service', hi: 'महाराष्ट्र वन सेवा' },
    desc: {
      mr: 'पर्यावरण, वनसंपत्ती, जैवविविधता व भूगोल विशेष रिव्हिजन साहित्य',
      en: 'Environment, Forest wealth, Biodiversity & Geography revision guides',
      hi: 'पर्यावरण, वन संपदा, जैव विविधता एवं भूगोल रिवीजन सामग्री',
    },
    resourcesCount: 39,
    iconName: 'TreePine',
  },
];

export const STUDY_MATERIALS_DATA: Product[] = [
  {
    id: 'mat-1',
    slug: 'mpsc-polity-revision-notes',
    title: {
      mr: 'MPSC भारतीय राज्यघटना व पंचायतराज — मास्टर रिव्हिजन नोट्स २०२६',
      en: 'MPSC Indian Polity & Constitution — Master Revision Notes 2026',
      hi: 'MPSC भारतीय संविधान एवं राजव्यवस्था — मास्टर रिवीजन नोट्स 2026',
    },
    subtitle: {
      mr: 'परीक्षेच्या दृष्टीने सर्वात महत्वाचे कलमे, घटनादुरुस्त्या व तक्ते',
      en: 'High-yield articles, constitutional amendments & comparative tables',
      hi: 'परीक्षा के लिए अति-महत्वपूर्ण अनुच्छेद, संशोधन एवं तुलनात्मक सारणियाँ',
    },
    description: {
      mr: 'MPSC राज्यसेवा व संयुक्त पूर्व परीक्षेसाठी तयार करण्यात आलेली ही अत्यंत लोकप्रिय रिव्हिजन ई-बुक आहे. यामध्ये घटनानिर्मिती, मूलभूत हक्क, मार्गदर्शक तत्वे, राष्ट्रपती, संसद, न्यायव्यवस्था आणि ७३ व ७४ वी घटनादुरुस्ती अत्यंत सोप्या आणि चित्रमय तक्त्यांच्या रूपात मांडली आहे.',
      en: 'A high-converting, exam-oriented digital revision book meticulously designed for MPSC Rajyaseva and Combine Group B & C aspirants. Includes quick comparative charts, landmark Supreme Court judgments, key constitutional articles, and 200+ PYQ mappings.',
      hi: 'MPSC राज्यसेवा और संयुक्त परीक्षा के लिए तैयार की गई यह अत्यंत लोकप्रिय रिवीजन ई-बुक है। इसमें संविधान निर्माण, मौलिक अधिकार, नीति निदेशक तत्व, संसद, न्यायपालिका एवं पंचायती राज को अत्यंत सरल भाषा और सारणियों में समझाया गया है।',
    },
    exam: 'MPSC',
    subject: 'Polity & Constitution',
    language: 'Marathi',
    materialType: 'Revision Notes',
    coverImage: '/images/mpsc_notes_book_mockup.jpg',
    samplePages: [
      '/images/mpsc_notes_book_mockup.jpg',
      '/images/mpsc_student_study.jpg',
    ],
    pages: 148,
    originalPrice: 299,
    discountedPrice: 149,
    rating: 4.9,
    reviewsCount: 482,
    lastUpdated: '15 Sep 2026',
    featured: true,
    bestseller: true,
    fileSize: '14.2 MB (Searchable PDF)',
    tableOfContents: [
      '१. भारतीय राज्यघटनेची निर्मिती व ठळक वैशिष्ट्ये',
      '२. सरनामा व मूलभूत हक्क (कलम १२ ते ३५)',
      '३. मार्गदर्शक तत्त्वे व मूलभूत कर्तव्ये',
      '४. केंद्रीय व राज्य कायदेमंडळ (संसद व विधानसभा)',
      '५. सर्वोच्च न्यायालय व उच्च न्यायालये',
      '६. ७३ वी व ७४ वी घटनादुरुस्ती (पंचायतराज)',
      '७. महत्वपूर्ण घटनात्मक आयोग व कायदे',
      '८. PYQ विश्लेषण व सराव प्रश्न',
    ],
    whatIsIncluded: [
      '१४८ पानांची हाय-डेफिनिशन टेक्स्ट-सर्चबल PDF',
      'सर्व महत्वाचे कलमे व घटनादुरुस्तींची फास्ट-ट्रॅक मेमरी शीट',
      'मागील १० वर्षांतील MPSC प्रश्नांचे संदर्भ',
      'कलर-कोडेड फ्लोचार्ट्स व तुलनात्मक तक्ते',
      'मोबाईल, टॅबलेट व लॅपटॉपवर सुलभ वाचनासाठी ऑप्टिमाइझ',
    ],
    tags: ['Polity', 'MPSC', 'Constitution', 'Revision', 'Bestseller'],
  },
  {
    id: 'mat-2',
    slug: 'maharashtra-geography-quick-revision',
    title: {
      mr: 'महाराष्ट्र भूगोल व प्राकृतिक रचना — नकाशे आधारित रिव्हिजन नोट्स',
      en: 'Maharashtra Geography & Physical Map Revision Book 2026',
      hi: 'महाराष्ट्र भूगोल एवं प्राकृतिक संरचना — मानचित्र आधारित रिवीजन नोट्स',
    },
    subtitle: {
      mr: '३५+ रंगीत नकाशे, जलप्रणाली, मृदा, खनिजे व प्रशासकीय विभाग',
      en: '35+ Color maps, river systems, soils, minerals & districts breakdown',
      hi: '35+ रंगीन मानचित्र, नदी प्रणाली, मिट्टी, खनिज एवं प्रशासनिक संभाग',
    },
    description: {
      mr: 'महाराष्ट्राच्या भूगोलावर येणारे सर्व प्रश्न अचूक सोडवण्यासाठी नकाशे-आधारित (Map-based) खास नोट्स. सह्याद्रीच्या उपरांगा, घाटरस्ते, नद्यांचे उगम, संगम आणि अभयारण्ये एका नजरेत पाठ होण्यासाठी डिझाइन केलेले.',
      en: 'High-density visual geography guide packed with high-resolution regional maps, river basins, mountain passes, wildlife sanctuaries, and census data comparisons for MPSC, Talathi and PSI exams.',
      hi: 'महाराष्ट्र के भूगोल पर आने वाले प्रश्नों के लिए मैप-आधारित विशेष नोट्स। सह्याद्रि की पर्वत श्रृंखलाएं, दर्रे, नदियों के संगम और अभयारण्यों का संपूर्ण सचित्र संकलन।',
    },
    exam: 'MPSC',
    subject: 'Maharashtra & World Geography',
    language: 'Marathi',
    materialType: 'Short Notes',
    coverImage: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 112,
    originalPrice: 249,
    discountedPrice: 119,
    rating: 4.8,
    reviewsCount: 318,
    lastUpdated: '08 Sep 2026',
    featured: true,
    bestseller: true,
    fileSize: '18.6 MB',
    tableOfContents: [
      '१. महाराष्ट्राची प्राकृतिक रचना व कोकण किनारपट्टी',
      '२. सह्याद्री पर्वत आणि प्रमुख घाटरस्ते',
      '३. गोदावरी, भीमा, कृष्णा आणि तापी जलप्रणाली',
      '४. हवामान, पर्जन्यमान आणि वनप्रकार',
      '५. खनिज संपत्ती व ऊर्जा प्रकल्प',
      '६. २०११ ची जनगणना व जिल्हावार आकडेवारी',
    ],
    whatIsIncluded: [
      '३५+ सुस्पष्ट रंगीत नकाशे व इन्फोग्राफिक्स',
      'घाटरस्ते व शिखरांची शॉर्ट ट्रिक मेमरी लिस्ट',
      'जिल्हावार महत्त्वाची वैशिष्ट्ये',
      'तलाठी व पोलीस भरती वारंवार विचारलेले प्रश्न',
    ],
    tags: ['Geography', 'Maharashtra', 'Maps', 'MPSC', 'Combine'],
  },
  {
    id: 'mat-3',
    slug: 'maharashtra-modern-history-notes',
    title: {
      mr: 'आधुनिक महाराष्ट्राचा इतिहास व समाजसुधारक — वन-स्टॉप रिव्हिजन',
      en: 'Modern History of Maharashtra & Social Reformers Compendium',
      hi: 'आधुनिक महाराष्ट्र का इतिहास एवं समाज सुधारक — संपूर्ण रिवीजन नोट्स',
    },
    subtitle: {
      mr: 'महात्मा फुले, डॉ. आंबेडकर, शाहू महाराज व १८५७ चा लढा',
      en: 'Phule, Shahu, Ambedkar, Freedom Struggle & Cultural Movements',
      hi: 'महात्मा फुले, डॉ. आंबेडकर, शाहू महाराज एवं 1857 का संग्राम',
    },
    description: {
      mr: 'MPSC व संयुक्त परीक्षांमध्ये हमखास १० ते १२ गुण मिळवून देणारा विभाग म्हणजे महाराष्ट्रातील समाजसुधारक व आधुनिक इतिहास. प्रत्येक समाजसुधारकाची संस्था, वृत्तपत्रे, ग्रंथ आणि महत्वाच्या घटनांची कालानुक्रमे सुटसुटीत मांडणी.',
      en: 'A high-impact revision manual focusing on the socio-religious reform movements in Maharashtra, prominent social reformers, journalistic foundations, and regional contributions to the Indian freedom struggle.',
      hi: 'महाराष्ट्र के प्रमुख समाज सुधारक, उनकी संस्थाएं, समाचार पत्र, कृतियां और भारतीय स्वतंत्रता संग्राम में योगदान का सटीक कालक्रमानुसार संकलन।',
    },
    exam: 'PSI',
    subject: 'Maharashtra & Indian History',
    language: 'Marathi',
    materialType: 'Revision Notes',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 136,
    originalPrice: 280,
    discountedPrice: 139,
    rating: 4.9,
    reviewsCount: 294,
    lastUpdated: '12 Sep 2026',
    featured: true,
    fileSize: '12.8 MB',
    tableOfContents: [
      '१. १८५७ चा उठाव आणि महाराष्ट्रातील केंद्र',
      '२. महात्मा जोतीराव फुले आणि सत्यशोधक समाज',
      '३. छत्रपती राजर्षी शाहू महाराज यांचे कार्य',
      '४. भारतरत्न डॉ. बाबासाहेब आंबेडकर व दलित चळवळ',
      '५. लोकमान्य टिळक, आगरकर आणि रानडे',
      '६. कामगार चळवळ, शेतकरी लढा व संयुक्त महाराष्ट्र चळवळ',
    ],
    whatIsIncluded: [
      'प्रत्येक समाजसुधारकाची संपूर्ण टाइमलाइन',
      'वृत्तपत्रे, पुस्तके व त्यांनी सुरू केलेल्या संस्थांची सूची',
      'वारंवार रिपीट होणाऱ्या तथ्यांची विशेष उजळणी',
    ],
    tags: ['History', 'Social Reformers', 'MPSC', 'PSI', 'STI'],
  },
  {
    id: 'mat-4',
    slug: 'indian-economy-one-liners-yearbook',
    title: {
      mr: 'भारतीय अर्थव्यवस्था व अर्थसंकल्प २०२६-२७ — एक्झाम वन-लाइनर्स',
      en: 'Indian Economy & Budget 2026-27 — Exam-Oriented One-Liners',
      hi: 'भारतीय अर्थव्यवस्था एवं बजट 2026-27 — परीक्षा उपयोगी वन-लाइनर्स',
    },
    subtitle: {
      mr: 'RBI पतधोरण, राष्ट्रीय उत्पन्न, दारिद्र्य, बँकिंग व सरकारी योजना',
      en: 'RBI policies, National Income, Poverty indices, Banking & Schemes',
      hi: 'RBI मौद्रिक नीति, राष्ट्रीय आय, गरीबी सूचकांक, बैंकिंग व योजनाएं',
    },
    description: {
      mr: 'अर्थशास्त्रातील क्लिष्ट संकल्पना सोप्या भाषेत समजून देणारे पुस्तक. महागाई, जीडीपी, आरबीआयचे रेपो दर, पंचवार्षिक योजना, नीति आयोग आणि नवीन केंद्रीय व महाराष्ट्र अर्थसंकल्पातील मुख्य आकडेवारी.',
      en: 'Clear, concise breakdown of macroeconomics, fiscal policies, banking regulations, agriculture economics, poverty estimation committees, and the latest Union and Maharashtra budgets.',
      hi: 'अर्थशास्त्र की जटिल अवधारणाओं को आसान भाषा में समझाने वाली ई-बुक। मुद्रास्फीति, जीडीपी, मौद्रिक नीति, बैंकिंग और सरकारी योजनाओं का संपूर्ण संकलन।',
    },
    exam: 'STI',
    subject: 'Indian Economy',
    language: 'Marathi',
    materialType: 'Short Notes',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 104,
    originalPrice: 220,
    discountedPrice: 99,
    rating: 4.7,
    reviewsCount: 215,
    lastUpdated: '18 Sep 2026',
    featured: false,
    fileSize: '9.4 MB',
    tableOfContents: [
      '१. राष्ट्रीय उत्पन्न व मोजमाप पद्धती',
      '२. चलनवाढ (महागाई) व चलनघट संकल्पना',
      '३. भारतीय बँकिंग व्यवस्था व रिझर्व्ह बँक',
      '४. दारिद्र्य व बेरोजगारी मापन समित्या',
      '५. विदेशी व्यापार, व्यवहारतोल व GST',
      '६. २०२६ मधील महत्वपूर्ण कल्याणकारी योजना',
    ],
    whatIsIncluded: [
      '५००+ अचूक एक्झाम ओरिएंटेड वन-लाइनर्स',
      'केंद्रीय व राज्य अर्थसंकल्पाचा मुख्य गोषवारा',
      'समित्या आणि त्यांच्या शिफारशींचे तक्ते',
    ],
    tags: ['Economy', 'STI', 'MPSC', 'Budget', 'OneLiners'],
  },
  {
    id: 'mat-5',
    slug: 'talathi-marathi-vyakaran-master-pdf',
    title: {
      mr: 'तलाठी व सरळसेवा (TCS/IBPS) मराठी व्याकरण — संपूर्ण प्रश्नसंच व शॉर्ट ट्रिक्स',
      en: 'TCS/IBPS Marathi Grammar — Complete Notes & 2000+ Practice MCQs',
      hi: 'TCS/IBPS मराठी व्याकरण — संपूर्ण नोट्स एवं 2000+ अभ्यास प्रश्न',
    },
    subtitle: {
      mr: 'प्रयोग, समास, समानार्थी, म्हणी, वाक्यरूपांतर व शब्दसंग्रह',
      en: 'Prayog, Samas, Synonyms, Proverbs, Clauses & Vocabulary Mastery',
      hi: 'प्रयोग, समास, पर्यायवाची, मुहावरे, वाक्य रूपांतर एवं शब्द भंडार',
    },
    description: {
      mr: 'TCS आणि IBPS पॅटर्ननुसार मराठी व्याकरणात २५ पैकी २५ गुण मिळवण्यासाठी सर्वोत्तम ई-बुक. प्रयोग, समास, संधी, विभक्ती यांसारखे कठीण घटक सोप्या शॉर्टकट ट्रिक्सने सोडवण्याची पद्धत यात दिली आहे.',
      en: 'The definitive Marathi grammar handbook tailored strictly to the TCS and IBPS recruitment patterns for Talathi, ZP, Nagar Parishad, and Clerk posts.',
      hi: 'TCS एवं IBPS पैटर्न पर आधारित मराठी व्याकरण की संपूर्ण ई-बुक। प्रयोग, समास, संधि, विभक्ति जैसे विषयों के आसान शॉर्टकट और 2000+ अभ्यास प्रश्न।',
    },
    exam: 'Talathi',
    subject: 'Marathi Grammar',
    language: 'Marathi',
    materialType: 'Practice Papers',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 180,
    originalPrice: 320,
    discountedPrice: 159,
    rating: 4.9,
    reviewsCount: 540,
    lastUpdated: '19 Sep 2026',
    featured: true,
    bestseller: true,
    fileSize: '16.5 MB',
    tableOfContents: [
      '१. वर्णविचार व वर्णमाला २०२६ अद्ययावत',
      '२. संधी व त्याचे प्रकार',
      '३. शब्दांच्या ८ जाती व विभक्ती विचार',
      '४. प्रयोग विचार (कर्तरी, कर्मणी, भावे)',
      '५. समास आणि त्याचे प्रकार ट्रिक्ससह',
      '६. अलंकार, वृत्त आणि रस',
      '७. शब्दसंग्रह (म्हणी, वाक्प्रचार, समानार्थी, विरुद्धार्थी)',
      '८. TCS मागील परीक्षांचे ५० सराव पेपर संच',
    ],
    whatIsIncluded: [
      '२,०००+ परीक्षेला विचारलेले प्रश्न व उत्तरे',
      'शॉर्टकट फॉर्म्युला टेबल',
      'TCS/IBPS पॅटर्नचे खास विश्लेषण',
    ],
    tags: ['Marathi Grammar', 'Talathi', 'TCS', 'IBPS', 'Bestseller'],
  },
  {
    id: 'mat-6',
    slug: 'current-affairs-yearbook-2026',
    title: {
      mr: 'वार्षिकी चालू घडामोडी २०२६ (जानेवारी ते सप्टेंबर) — एक्झाम स्पेशल डायजेस्ट',
      en: 'Current Affairs Yearbook 2026 (Jan - Sep) — Exam Special Digest',
      hi: 'वार्षिकी करंट अफेयर्स 2026 (जनवरी से सितंबर) — परीक्षा स्पेशल डाइजेस्ट',
    },
    subtitle: {
      mr: 'पुरस्कार, क्रीडा, नियुक्त्या, आंतरराष्ट्रीय घडामोडी व महाराष्ट्र विशेष',
      en: 'Awards, Sports, Appointments, International events & Maharashtra focus',
      hi: 'पुरस्कार, खेल, नियुक्तियां, अंतर्राष्ट्रीय घटनाक्रम एवं महाराष्ट्र विशेष',
    },
    description: {
      mr: 'स्पर्धा परीक्षांच्या सर्व आगामी पेपर्ससाठी मागील ९ महिन्यांच्या अत्यंत निवडक आणि परीक्षोपयोगी चालू घडामोडींचे मासिकवार व विषयवार संकलन. वन-लाइनर्स, फ्लोचार्ट्स आणि ३००+ सराव बहुपर्यायी प्रश्न.',
      en: 'Curated comprehensive compilation of January to September 2026 current affairs. Perfectly segmented into National, Maharashtra state initiatives, Summits, Defense drills, and Science breakthroughs.',
      hi: 'प्रतियोगी परीक्षाओं के लिए पिछले 9 महीनों के अति-महत्वपूर्ण करंट अफेयर्स का विषयवार एवं माहवार संकलन। 300+ अभ्यास बहुविकल्पीय प्रश्न शामिल।',
    },
    exam: 'MPSC',
    subject: 'Current Affairs',
    language: 'Bilingual',
    materialType: 'Yearbooks',
    coverImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 164,
    originalPrice: 250,
    discountedPrice: 129,
    rating: 4.8,
    reviewsCount: 388,
    lastUpdated: '20 Sep 2026',
    featured: true,
    fileSize: '15.1 MB',
    tableOfContents: [
      '१. राष्ट्रीय व आंतरराष्ट्रीय महत्वाच्या घटना',
      '२. महाराष्ट्र शासन नवीन धोरणे व योजना',
      '३. क्रीडा विश्व: ऑलिम्पिक, क्रिकेट व इतर स्पर्धा',
      '४. विज्ञान व तंत्रज्ञान: इस्रो, डीआरडीओ मोहिमा',
      '५. आर्थिक घडामोडी व निर्देशांक',
      '६. चर्चित व्यक्ती, पुरस्कार व सन्मान',
      '७. ३००+ सराव प्रश्नसंच स्पष्टीकरणासह',
    ],
    whatIsIncluded: [
      'महिन्यानुसार मुद्देसूद मांडणी',
      'परीक्षेसाठी थेट प्रश्न विचारले जाणारे टेबल चार्ट्स',
      '३०० सराव MCQs',
    ],
    tags: ['Current Affairs', 'Yearbook', 'MPSC', 'Talathi', 'Police Bharti'],
  },
  {
    id: 'mat-7',
    slug: 'police-bharti-gk-fastrack-notes',
    title: {
      mr: 'पोलीस भरती सामान्य ज्ञान (GK) फास्टट्रॅक ई-बुक — ५००० वन-लाइनर्स',
      en: 'Maharashtra Police Bharti General Knowledge Fast-Track E-Book',
      hi: 'महाराष्ट्र पुलिस भर्ती सामान्य ज्ञान (GK) फास्टट्रैक ई-बुक — 5000 वन-लाइनर्स',
    },
    subtitle: {
      mr: 'इतिहास, भूगोल, विज्ञान, नागरिकशास्त्र व जिल्हा विशेष माहिती',
      en: 'History, Geography, Science, Civics & District special knowledge',
      hi: 'इतिहास, भूगोल, सामान्य विज्ञान, नागरिक शास्त्र एवं जिला विशेष जानकारी',
    },
    description: {
      mr: 'महाराष्ट्र पोलीस शिपाई, चालक व कारागृह पोलीस पदांसाठी १००% अभ्यासक्रम कव्हर करणारे ई-पुस्तक. कमी वेळेत जास्तीत जास्त रिव्हिजन करण्यासाठी अत्यंत प्रभावी.',
      en: 'Designed specifically for Maharashtra Police Constable recruitment aspirants. Concentrated 5000+ one-liners covering General Knowledge, Maharashtra districts, and basic law.',
      hi: 'महाराष्ट्र पुलिस सिपाही भर्ती परीक्षा के लिए विशेष रूप से तैयार 5000+ वन-लाइनर्स। कम समय में अधिकतम रिवीजन के लिए सर्वोत्तम।',
    },
    exam: 'Police Bharti',
    subject: 'General Science',
    language: 'Marathi',
    materialType: 'Short Notes',
    coverImage: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 120,
    originalPrice: 199,
    discountedPrice: 89,
    rating: 4.8,
    reviewsCount: 410,
    lastUpdated: '14 Sep 2026',
    featured: false,
    fileSize: '10.2 MB',
    tableOfContents: [
      '१. महाराष्ट्राचा संक्षिप्त इतिहास व शूरवीर',
      '२. महाराष्ट्राचा भूगोल व पोलीस आयुक्तालये',
      '३. भारताचे संविधान व नागरिक कर्तव्ये',
      '४. सामान्य विज्ञान (भौतिक, रसायन, जीवशास्त्र)',
      '५. चालू घडामोडी व पुरस्कार',
      '६. मागील ५ वर्षांचे पोलीस भरती पेपर्स गोषवारा',
    ],
    whatIsIncluded: [
      '५००० सुटसुटीत वन-लाइनर्स',
      '३६ जिल्ह्यांची महत्त्वाची माहिती',
      'मोबाईलवर ऑफलाइन वाचण्याची सोय',
    ],
    tags: ['Police Bharti', 'GK', 'FastTrack', 'OneLiners'],
  },
  {
    id: 'mat-8',
    slug: 'free-mpsc-prelims-syllabus-micro-topics',
    title: {
      mr: 'MPSC राज्यसेवा व संयुक्त पूर्व परीक्षा — मायक्रो सिलॅबस व बुकलिस्ट (मोफत)',
      en: 'MPSC Prelims Micro Syllabus & Verified Booklist Guide (FREE)',
      hi: 'MPSC प्रीलिम्स माइक्रो सिलेबस एवं बुकलिस्ट गाइड (मुफ्त)',
    },
    subtitle: {
      mr: 'प्रत्येक विषयातील हाय-वेटेज टॉपिक्स आणि टॉपर्सची संदर्भ पुस्तके',
      en: 'High-weightage topics breakdown and topper recommended reading list',
      hi: 'प्रत्येक विषय के हाई-वेटेज टॉपिक्स एवं टॉपर्स की अनुशंसित पुस्तकें',
    },
    description: {
      mr: 'स्पर्धा परीक्षेचा अभ्यास सुरू करणाऱ्या प्रत्येक विद्यार्थ्यासाठी अनिवार्य मोफत मार्गदर्शक पुस्तिका. आयोगाच्या अभ्यासक्रमाचे घटकवार आणि उपघटकवार मायक्रो वर्गीकरण.',
      en: 'Free strategic blueprint for all civil services aspirants. Features detailed micro-topic breakdowns, weightage heatmaps for the past 7 years, and step-by-step reading roadmap.',
      hi: 'सभी प्रतियोगी छात्रों के लिए निःशुल्क रणनीतिक गाइड। आयोग के पाठ्यक्रम का विस्तृत माइक्रो वर्गीकरण और पिछले 7 वर्षों का विषयवार विश्लेषण।',
    },
    exam: 'MPSC',
    subject: 'Polity & Constitution',
    language: 'Marathi',
    materialType: 'Study Guides',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    samplePages: [
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    ],
    pages: 42,
    originalPrice: 99,
    discountedPrice: 0,
    isFree: true,
    rating: 5.0,
    reviewsCount: 890,
    lastUpdated: '10 Sep 2026',
    featured: true,
    fileSize: '4.8 MB',
    tableOfContents: [
      '१. परीक्षा स्वरूप व गुणदान पद्धती',
      '२. इतिहास, भूगोल, राज्यघटना मायक्रो सिलॅबस',
      '३. विज्ञान व अर्थशास्त्र प्राधान्य घटक',
      '४. चालू घडामोडी कशा तयार कराव्यात?',
      '५. प्रामाणिक संदर्भ पुस्तकांची अधिकृत यादी',
    ],
    whatIsIncluded: [
      '१००% मोफत तात्काळ डिजिटल डाउनलोड',
      'घटकनिहाय गुणभार तक्ता',
      'दैनिक अभ्यास वेळापत्रक फॉरमॅट',
    ],
    tags: ['Free', 'Syllabus', 'Booklist', 'Strategy', 'MPSC'],
  },
];

export const COURSES_DATA: Course[] = [
  {
    id: 'course-1',
    slug: 'mpsc-complete-polity-revision-batch',
    title: {
      mr: 'MPSC भारतीय राज्यघटना व पंचायतराज — संपूर्ण रिव्हिजन बॅच २०२६',
      en: 'MPSC Complete Indian Polity & Governance Revision Masterclass',
      hi: 'MPSC भारतीय राजव्यवस्था एवं पंचायती राज — संपूर्ण रिवीजन बैच 2026',
    },
    exam: 'MPSC',
    instructor: {
      name: 'प्रा. सचिन कदम (Ex-Deputy Collector Rank)',
      role: 'वरिष्ठ मार्गदर्शक, स्पर्धा परीक्षा',
      experience: '१२+ वर्षे अध्यापन अनुभव',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    },
    language: 'Marathi + English',
    duration: '४५ तास (Live + Recorded)',
    type: 'Live + Recorded',
    validity: '६ महिने अमर्याद प्रवेश',
    rating: 4.9,
    enrolledCount: 1240,
    originalPrice: 1999,
    discountedPrice: 799,
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    modules: [
      { title: 'मॉड्यूल १: राज्यघटनेचा पाया आणि निर्मिती', lessons: 8, hours: '७ तास' },
      { title: 'मॉड्यूल २: मूलभूत हक्क, मार्गदर्शक तत्वे व कर्तव्ये', lessons: 10, hours: '९ तास' },
      { title: 'मॉड्यूल ३: संसद व राज्य कायदेमंडळ सखोल', lessons: 12, hours: '११ तास' },
      { title: 'मॉड्यूल ४: न्यायव्यवस्था व महत्वाची घटनात्मक प्रकरणे', lessons: 8, hours: '८ तास' },
      { title: 'मॉड्यूल ५: पंचायतराज, स्थानिक स्वराज्य व PYQ टेस्ट्स', lessons: 10, hours: '१० तास' },
    ],
    whatYouWillLearn: [
      'राज्यघटनेतील सर्व महत्वाचे ३९५+ कलमे लक्षात ठेवण्याच्या युक्त्या',
      'MPSC प्रिलिम्स आणि मेन्ससाठी आवश्यक उत्तरे कशी लिहावीत',
      '२०१३ ते २०२५ पर्यंतच्या सर्व प्रश्नांचे लाईव्ह विश्लेषण',
      'कोर्ससोबत सर्व डिजिटल PDF नोट्स मोफत समाविष्ट',
    ],
  },
  {
    id: 'course-2',
    slug: 'talathi-saralseva-crash-course',
    title: {
      mr: 'तलाठी व जिल्हा परिषद भरती — TCS पॅटर्न क्रॅश कोर्स २०२६',
      en: 'Talathi & ZP Bharti — TCS/IBPS Pattern Fast-Track Crash Course',
      hi: 'तलाठी एवं जिला परिषद भर्ती — TCS/IBPS पैटर्न क्रैश कोर्स 2026',
    },
    exam: 'Talathi',
    instructor: {
      name: 'आनंद पाटील & टीम',
      role: 'TCS/IBPS पॅटर्न एक्सपर्ट्स',
      experience: '८+ वर्षे अनुभव',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    language: 'Marathi',
    duration: '६० तास संपूर्ण रिव्हिजन',
    type: 'Recorded HD',
    validity: '४ महिने',
    rating: 4.8,
    enrolledCount: 2180,
    originalPrice: 1499,
    discountedPrice: 499,
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    modules: [
      { title: 'मराठी व्याकरण संपूर्ण TCS पॅटर्न', lessons: 14, hours: '१५ तास' },
      { title: 'इंग्रजी व्याकरण व व्होकॅब्युलरी ट्रिक्स', lessons: 12, hours: '१४ तास' },
      { title: 'अंकगणित व बुद्धिमत्ता जलद गती युक्त्या', lessons: 16, hours: '१८ तास' },
      { title: 'सामान्य ज्ञान व चालू घडामोडी', lessons: 12, hours: '१३ तास' },
    ],
    whatYouWillLearn: [
      'TCS च्या नवीन पॅटर्ननुसार प्रश्नांची अचूक निवड',
      'वेळेचे व्यवस्थापन आणि शॉर्टकट फॉर्म्युले',
      '५ पूर्ण लांबीचे मॉक टेस्ट पेपर्स विश्लेषणासह',
    ],
  },
];

export const PYQS_DATA: PYQItem[] = [
  {
    id: 'pyq-1',
    exam: 'MPSC',
    year: 2025,
    subject: 'Polity & Constitution',
    topic: 'Fundamental Rights (मूलभूत हक्क)',
    question: {
      mr: 'खालीलपैकी कोणत्या घटनादुरुस्तीने भारतीय राज्यघटनेतील संपत्तीचा हक्क (Right to Property) मूलभूत हक्कातून वगळण्यात आला?',
      en: 'By which of the following Constitutional Amendments was the Right to Property removed from the list of Fundamental Rights?',
      hi: 'निम्नलिखित में से किस संविधान संशोधन द्वारा संपत्ति के अधिकार को मौलिक अधिकारों की सूची से हटाया गया था?',
    },
    options: [
      { id: 1, text: { mr: '४२ वी घटनादुरुस्ती (१९७६)', en: '42nd Amendment (1976)', hi: '42वां संविधान संशोधन (1976)' } },
      { id: 2, text: { mr: '४४ वी घटनादुरुस्ती (१९७८)', en: '44th Amendment (1978)', hi: '44वां संविधान संशोधन (1978)' } },
      { id: 3, text: { mr: '५२ वी घटनादुरुस्ती (१९८५)', en: '52nd Amendment (1985)', hi: '52वां संविधान संशोधन (1985)' } },
      { id: 4, text: { mr: '८६ वी घटनादुरुस्ती (२००२)', en: '86th Amendment (2002)', hi: '86वां संविधान संशोधन (2002)' } },
    ],
    correctOption: 2,
    explanation: {
      mr: 'स्पष्टीकरण: ४४ व्या घटनादुरुस्ती कायदा, १९७८ अन्वये कलम ३१ मधील "संपत्तीचा अधिकार" हा मूलभूत हक्कातून काढून टाकण्यात आला. सध्या हा अधिकार भाग १२ मधील कलम ३००-A अंतर्गत केवळ "कायदेशीर अधिकार" (Legal Right) म्हणून ठेवण्यात आला आहे.',
      en: 'Explanation: By the 44th Constitutional Amendment Act of 1978, the Right to Property was omitted from the list of Fundamental Rights (under Article 19(1)(f) and Article 31). It is now made a legal/constitutional right under Article 300-A in Part XII.',
      hi: 'व्याख्या: 44वें संविधान संशोधन अधिनियम, 1978 द्वारा संपत्ति के अधिकार को मौलिक अधिकारों की सूची से हटाकर अनुच्छेद 300-A के तहत केवल एक विधिक (कानूनी) अधिकार बनाया गया।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'pyq-2',
    exam: 'MPSC',
    year: 2024,
    subject: 'Maharashtra & World Geography',
    topic: 'River Systems (महाराष्ट्राची जलप्रणाली)',
    question: {
      mr: 'गोदावरी नदी खोऱ्याने महाराष्ट्राचे सुमारे किती टक्के भौगोलिक क्षेत्र व्यापलेले आहे?',
      en: 'Approximately what percentage of Maharashtra’s geographical area is drained by the Godavari River basin?',
      hi: 'गोदावरी नदी बेसिन द्वारा महाराष्ट्र के कुल भौगोलिक क्षेत्र का लगभग कितने प्रतिशत भाग घेरा गया है?',
    },
    options: [
      { id: 1, text: { mr: '३४.२%', en: '34.2%', hi: '34.2%' } },
      { id: 2, text: { mr: '४९.५% (सुमारे ५०%)', en: '49.5% (approx 50%)', hi: '49.5% (लगभग 50%)' } },
      { id: 3, text: { mr: '२२.६%', en: '22.6%', hi: '22.6%' } },
      { id: 4, text: { mr: '६१.३%', en: '61.3%', hi: '61.3%' } },
    ],
    correctOption: 2,
    explanation: {
      mr: 'स्पष्टीकरण: गोदावरी हे महाराष्ट्रातील सर्वात मोठे नदी खोरे असून ते राज्याच्या एकूण भौगोलिक क्षेत्राच्या सुमारे ४९.५% (अंदाजे ५०%) क्षेत्र व्यापते. गोदावरी नदीचा उगम नाशिक जिल्ह्यातील त्र्यंबकेश्वर येथे होतो.',
      en: 'Explanation: Godavari is the largest river basin in Maharashtra, covering approximately 49.5% (nearly half) of the state’s total land area. It originates at Trimbakeshwar in Nashik district.',
      hi: 'व्याख्या: गोदावरी महाराष्ट्र का सबसे बड़ा नदी बेसिन है, जो राज्य के कुल भौगोलिक क्षेत्र का लगभग 49.5% भाग कवर करता है। इसका उद्गम नासिक जिले के त्र्यंबकेश्वर से होता है।',
    },
    difficulty: 'Easy',
  },
  {
    id: 'pyq-3',
    exam: 'PSI',
    year: 2024,
    subject: 'Maharashtra & Indian History',
    topic: 'Social Reformers (महाराष्ट्रातील समाजसुधारक)',
    question: {
      mr: 'सत्यशोधक समाजाची स्थापना महात्मा जोतीराव फुले यांनी खालीलपैकी कोणत्या वर्षी केली?',
      en: 'In which year did Mahatma Jyotirao Phule establish the Satyashodhak Samaj?',
      hi: 'महात्मा ज्योतिराव फुले ने किस वर्ष सत्यशोधक समाज की स्थापना की थी?',
    },
    options: [
      { id: 1, text: { mr: '२४ सप्टेंबर १८७३', en: '24 September 1873', hi: '24 सितंबर 1873' } },
      { id: 2, text: { mr: '१ मे १८७५', en: '1 May 1875', hi: '1 मई 1875' } },
      { id: 3, text: { mr: '१४ जानेवारी १८८२', en: '14 January 1882', hi: '14 जनवरी 1882' } },
      { id: 4, text: { mr: '२ ऑक्टोबर १८६९', en: '2 October 1869', hi: '2 अक्टूबर 1869' } },
    ],
    correctOption: 1,
    explanation: {
      mr: 'स्पष्टीकरण: महात्मा जोतीराव फुले यांनी २४ सप्टेंबर १८७३ रोजी पुणे येथे सत्यशोधक समाजाची स्थापना केली. "सर्वसाक्षी जगत्पती । त्याला नकोच मध्यस्थी ॥" हे या समाजाचे मुख्य ब्रीदवाक्य होते.',
      en: 'Explanation: Mahatma Jyotirao Phule founded Satyashodhak Samaj on 24th September 1873 in Pune to liberate the oppressed classes and promote education and social equality.',
      hi: 'व्याख्या: महात्मा ज्योतिराव फुले ने 24 सितंबर 1873 को पुणे में सत्यशोधक समाज की स्थापना की। इसका मुख्य उद्देश्य शूद्रों और अति-शूद्रों को सामाजिक और धार्मिक शोषण से मुक्ति दिलाना था।',
    },
    difficulty: 'Medium',
  },
  {
    id: 'pyq-4',
    exam: 'Talathi',
    year: 2025,
    subject: 'Marathi Grammar',
    topic: 'समास (Compounds)',
    question: {
      mr: '"यथाशक्ती" या शब्दाचा समास खालीलपैकी कोणता आहे?',
      en: 'Which type of Samas (compound) is the word "Yathashakti"?',
      hi: '"यथाशक्ति" शब्द में निम्नलिखित में से कौन सा समास है?',
    },
    options: [
      { id: 1, text: { mr: 'तत्पुरुष समास', en: 'Tatpurush Samas', hi: 'तत्पुरुष समास' } },
      { id: 2, text: { mr: 'अव्ययीभाव समास', en: 'Avyayibhav Samas', hi: 'अव्ययीभाव समास' } },
      { id: 3, text: { mr: 'द्वंद्व समास', en: 'Dvandva Samas', hi: 'द्वंद्व समास' } },
      { id: 4, text: { mr: 'बहुव्रीही समास', en: 'Bahuvrihi Samas', hi: 'बहुव्रीहि समास' } },
    ],
    correctOption: 2,
    explanation: {
      mr: 'स्पष्टीकरण: "यथाशक्ती" म्हणजे "शक्तीप्रमाणे". ज्या सामासिक शब्दातील पहिले पद मुख्य असते आणि तो शब्द क्रियाविशेषणाप्रमाणे कार्य करतो, त्याला "अव्ययीभाव समास" म्हणतात. उदा. आजन्म, प्रतिदिन, यथाशक्ती.',
      en: 'Explanation: In Avyayibhav Samas, the first component is predominant and functions as an adverb. "Yathashakti" means according to one’s strength.',
      hi: 'व्याख्या: जिस समास का पहला पद प्रधान हो और समस्त पद क्रियाविशेषण अव्यय का कार्य करे, उसे अव्ययीभाव समास कहते हैं। यथाशक्ति = शक्ति के अनुसार।',
    },
    difficulty: 'Easy',
  },
];

export const EXAM_UPDATES_DATA: ExamUpdate[] = [
  {
    id: 'upd-1',
    slug: 'mpsc-rajyaseva-prelims-2026-admit-card',
    title: {
      mr: 'MPSC राज्यसेवा पूर्व परीक्षा २०२६ — प्रवेशपत्र (Admit Card) अधिकृत प्रसिद्ध',
      en: 'MPSC Rajyaseva Prelims 2026 — Official Hall Tickets Released',
      hi: 'MPSC राज्यसेवा प्रारंभिक परीक्षा 2026 — आधिकारिक एडमिट कार्ड जारी',
    },
    exam: 'MPSC',
    category: 'Admit Card',
    badge: 'ADMIT CARD',
    publishedDate: '२१ सप्टेंबर २०२६',
    lastDate: '०४ ऑक्टोबर २०२६',
    examDate: '०४ ऑक्टोबर २०२६ (रविवार)',
    shortSummary: {
      mr: 'महाराष्ट्र लोकसेवा आयोगातर्फे राज्यसेवा पूर्व परीक्षा २०२६ साठी उमेदवारांचे हॉल तिकीट आयोगाच्या संकेतस्थळावर उपलब्ध करून देण्यात आले आहे.',
      en: 'Maharashtra Public Service Commission has officially published the admit cards for Civil Services Preliminary Examination 2026 on mpsconline.gov.in.',
      hi: 'महाराष्ट्र लोक सेवा आयोग ने सिविल सेवा प्रारंभिक परीक्षा 2026 के लिए हॉल टिकट आधिकारिक वेबसाइट पर जारी कर दिए हैं।',
    },
    fullContent: {
      mr: 'महाराष्ट्र लोकसेवा आयोगातर्फे घेण्यात येणाऱ्या राज्यसेवा पूर्व परीक्षा २०२६ साठी प्रवेशपत्रे आता उपलब्ध झाली आहेत. उमेदवारांनी आपले लॉगिन आयडी व पासवर्ड टाकून तात्काळ प्रवेशपत्र डाऊनलोड करावे. परीक्षा केंद्रावर जाताना अधिकृत ओळखपत्र (आधार कार्ड / पॅन कार्ड / ड्रायव्हिंग लायसन्स) सोबत ठेवणे अनिवार्य आहे.',
      en: 'The Maharashtra Public Service Commission (MPSC) has officially activated the download link for the Rajyaseva Preliminary Examination 2026 hall tickets. Candidates must log in to the student portal and verify their center details.',
      hi: 'महाराष्ट्र लोक सेवा आयोग द्वारा आयोजित राज्यसेवा प्रारंभिक परीक्षा 2026 के लिए एडमिट कार्ड जारी कर दिए गए हैं। अभ्यर्थी अपना हॉल टिकट डाउनलोड करें।',
    },
    officialLink: 'https://mpsc.gov.in',
  },
  {
    id: 'upd-2',
    slug: 'talathi-bharti-waiting-list-result-2026',
    title: {
      mr: 'महाराष्ट्र तलाठी भरती २०२६ — सुधारित प्रतीक्षा यादी व अंतिम निवड जाहीर',
      en: 'Maharashtra Talathi Recruitment 2026 — Final Selection & Waiting List Released',
      hi: 'महाराष्ट्र तलाठी भर्ती 2026 — संशोधित प्रतीक्षा सूची एवं अंतिम चयन सूची जारी',
    },
    exam: 'Talathi',
    category: 'Results',
    badge: 'RESULT',
    publishedDate: '१९ सप्टेंबर २०२६',
    shortSummary: {
      mr: 'महसूल विभागामार्फत राज्यातील सर्व जिल्ह्यांची तलाठी पदाची अंतिम निवड यादी व प्रतीक्षा यादी प्रसिद्ध करण्यात आली आहे.',
      en: 'Revenue department has declared the comprehensive final district-wise merit list and waiting list for Talathi post across all divisions.',
      hi: 'राजस्व विभाग द्वारा राज्य के सभी जिलों की तलाठी भर्ती की अंतिम चयन सूची एवं प्रतीक्षा सूची जारी कर दी गई है।',
    },
    fullContent: {
      mr: 'महाराष्ट्र शासनाच्या महसूल व वन विभागाकडून तलाठी संवर्गातील पदांसाठी प्रतीक्षा यादीतून निवड झालेल्या उमेदवारांची कागदपत्र पडताळणी तारीख जाहीर करण्यात आली आहे. पात्र उमेदवारांनी आपापल्या जिल्हाधिकारी कार्यालयात विहित मुदतीत हजर राहावे.',
      en: 'District collectorates across Maharashtra have initiated document verification rounds for qualified candidates from the waiting list.',
      hi: 'राजस्व विभाग द्वारा सभी चयनित अभ्यर्थियों के दस्तावेज़ सत्यापन की तिथियां घोषित कर दी गई हैं।',
    },
    officialLink: 'https://mahabhumi.gov.in',
  },
  {
    id: 'upd-3',
    slug: 'police-bharti-physical-dates-announcement',
    title: {
      mr: 'महाराष्ट्र पोलीस शिपाई भरती — मैदानी चाचणी (Physical Test) वेळापत्रक जाहीर',
      en: 'Maharashtra Police Bharti — Physical Test Dates & Ground Allotment Schedule',
      hi: 'महाराष्ट्र पुलिस सिपाही भर्ती — शारीरिक दक्षता परीक्षा (Physical Test) शेड्यूल घोषित',
    },
    exam: 'Police Bharti',
    category: 'Important Dates',
    badge: 'NEW',
    publishedDate: '१८ सप्टेंबर २०२६',
    lastDate: '१५ ऑक्टोबर २०२६',
    examDate: '२५ ऑक्टोबर ते १० नोव्हेंबर २०२६',
    shortSummary: {
      mr: 'पोलीस महासंचालक कार्यालयाकडून राज्यातील १७,०००+ पोलीस पदांसाठीच्या मैदानी चाचणीचे केंद्रनिहाय वेळापत्रक घोषित.',
      en: 'DGP Maharashtra announces ground schedule for 17,000+ Police Constable & Driver physical efficiency tests starting next month.',
      hi: 'महाराष्ट्र पुलिस महानिदेशक कार्यालय ने 17,000+ पदों के लिए शारीरिक दक्षता परीक्षा की तिथियां जारी की हैं।',
    },
    fullContent: {
      mr: 'राज्यातील पोलीस शिपाई व चालक पदांसाठी अर्ज केलेल्या लाखो उमेदवारांसाठी दिलासादायक बातमी. येत्या २५ ऑक्टोबरपासून मैदानी चाचण्या सुरू होणार असून, उमेदवारांना आपापल्या पोलीस आयुक्तालय / अधीक्षक कार्यालयानुसार तारीख व मैदानाचे नाव एसएमएस व ईमेलद्वारे कळवण्यात येईल.',
      en: 'The physical test for Maharashtra Police Constable recruitment will commence on October 25. Candidates are advised to download the physical guidelines document.',
      hi: 'महाराष्ट्र पुलिस भर्ती की शारीरिक दक्षता परीक्षा 25 अक्टूबर से प्रारंभ होगी। अभ्यर्थी आधिकारिक गाइडलाइंस डाउनलोड करें।',
    },
    officialLink: 'https://policerecruitment.mahait.org',
  },
  {
    id: 'upd-4',
    slug: 'mpsc-combine-group-b-c-advertisement-2026',
    title: {
      mr: 'MPSC संयुक्त गट-ब व गट-क परीक्षा २०२६ — एकूण ३,२५० पदांची महाभरती जाहिरात',
      en: 'MPSC Combine Group B & C 2026 Notification — 3,250 Vacancies Announced',
      hi: 'MPSC संयुक्त ग्रुप B एवं C परीक्षा 2026 — कुल 3,250 पदों की महाभर्ती विज्ञापन',
    },
    exam: 'PSI',
    category: 'Exam Notifications',
    badge: 'IMPORTANT',
    publishedDate: '१६ सप्टेंबर २०२६',
    lastDate: '०८ ऑक्टोबर २०२६',
    examDate: '२८ नोव्हेंबर २०२६',
    shortSummary: {
      mr: 'PSI, STI, ASO, दुय्यम निबंधक, कर सहाय्यक आणि लिपिक-टंकलेखक पदांसाठी अर्ज प्रक्रिया सुरू.',
      en: 'Official notification out for PSI, STI, ASO, Sub-Registrar, Tax Assistant and Clerks. Online application window active.',
      hi: 'PSI, STI, ASO, उप पंजीयक, कर सहायक एवं लिपिक पदों के लिए ऑनलाइन आवेदन प्रक्रिया शुरू।',
    },
    fullContent: {
      mr: 'महाराष्ट्र लोकसेवा आयोगाने २०२६ च्या संयुक्त पूर्व परीक्षेची अधिकृत जाहिरात प्रसिद्ध केली आहे. एकूण ३,२५० जागा असून PSI पदासाठी ६२०, STI साठी ३४० आणि ASO साठी १८० जागांचा समावेश आहे. अर्ज करण्याची अंतिम मुदत ८ ऑक्टोबर २०२६ आहे.',
      en: 'Online applications are invited for 3,250 posts under Maharashtra Non-Gazetted Group B & C Services Joint Prelims 2026. Deadline is 8 October 2026.',
      hi: 'महाराष्ट्र लोक सेवा आयोग ने संयुक्त ग्रुप B एवं C के 3,250 रिक्त पदों पर भर्ती के लिए आवेदन आमंत्रित किए हैं।',
    },
    officialLink: 'https://mpsc.gov.in',
  },
];

export const IMPORTANT_DATES_DATA: ImportantDateItem[] = [
  {
    id: 'date-1',
    exam: 'MPSC',
    event: {
      mr: 'MPSC राज्यसेवा पूर्व परीक्षा २०२६',
      en: 'MPSC Rajyaseva Preliminary Exam 2026',
      hi: 'MPSC राज्यसेवा प्रारंभिक परीक्षा 2026',
    },
    startDate: '२१ सप्टेंबर २०२६',
    lastDate: '०४ ऑक्टोबर २०२६',
    status: 'Closing Soon',
    category: 'Exam',
  },
  {
    id: 'date-2',
    exam: 'PSI',
    event: {
      mr: 'संयुक्त गट-ब व क अर्ज करण्याची मुदत',
      en: 'Combine Group B & C Online Form Window',
      hi: 'संयुक्त ग्रुप B एवं C ऑनलाइन आवेदन तिथि',
    },
    startDate: '१६ सप्टेंबर २०२६',
    lastDate: '०८ ऑक्टोबर २०२६',
    status: 'Active',
    category: 'Form',
  },
  {
    id: 'date-3',
    exam: 'Police Bharti',
    event: {
      mr: 'महाराष्ट्र पोलीस भरती मैदानी चाचणी',
      en: 'Police Bharti Physical Tests Phase 1',
      hi: 'पुलिस भर्ती शारीरिक दक्षता परीक्षा फेज 1',
    },
    startDate: '२५ ऑक्टोबर २०२६',
    lastDate: '१० नोव्हेंबर २०२६',
    status: 'Upcoming',
    category: 'Exam',
  },
  {
    id: 'date-4',
    exam: 'TET / TAIT',
    event: {
      mr: 'महाराष्ट्र TET शिक्षक पात्रता परीक्षा २०२६',
      en: 'MAHA TET Teacher Eligibility Test 2026',
      hi: 'महाराष्ट्र शिक्षक पात्रता परीक्षा 2026',
    },
    startDate: '०१ ऑक्टोबर २०२६',
    lastDate: '२२ ऑक्टोबर २०२६',
    status: 'Upcoming',
    category: 'Form',
  },
  {
    id: 'date-5',
    exam: 'सरळसेवा',
    event: {
      mr: 'जिल्हा परिषद आरोग्य सेवक लेखी परीक्षा निकाल',
      en: 'ZP Arogya Sevak Written Exam Result',
      hi: 'जिला परिषद आरोग्य सेवक लिखित परीक्षा परिणाम',
    },
    startDate: '२८ सप्टेंबर २०२६',
    lastDate: '३० सप्टेंबर २०२६',
    status: 'Upcoming',
    category: 'Result',
  },
];

export const CURRENT_AFFAIRS_DATA: CurrentAffairItem[] = [
  {
    id: 'ca-1',
    title: {
      mr: 'महाराष्ट्र शासनाचा नवीन "मुख्यमंत्री युवा कार्यप्रशिक्षण" उपक्रम जाहीर',
      en: 'Maharashtra Launches CM Youth Apprenticeship & Skill Initiative 2026',
      hi: 'महाराष्ट्र सरकार ने घोषित किया नया "मुख्यमंत्री युवा कार्यप्रशिक्षण" कार्यक्रम',
    },
    category: 'Maharashtra',
    date: '२१ सप्टेंबर २०२६',
    summary: {
      mr: 'राज्यातील पदवीधर व पदविकाधारक तरुणांना दरमहा ₹१०,००० पर्यंत विद्यावेतन देणारी नवीन योजना.',
      en: 'Key initiative providing hands-on industrial training with monthly stipends up to ₹10,000 for state youth.',
      hi: 'राज्य के युवाओं को मासिक ₹10,000 तक का वजीफा प्रदान करने वाली महत्वपूर्ण कौशल प्रशिक्षण योजना।',
    },
    points: {
      mr: [
        'महाराष्ट्र राज्य कौशल्य विकास विभागाने ही योजना अधिकृतपणे कार्यान्वित केली.',
        'उमेदवारांना ६ महिन्यांचे थेट शासकीय व खासगी आस्थापनांमध्ये प्रशिक्षण दिले जाईल.',
        'MPSC चालू घडामोडीसाठी या योजनेचे नाव, पात्रता आणि विद्यावेतनाची रक्कम विचारली जाऊ शकते.',
      ],
      en: [
        'Officially rolled out by Maharashtra Skill Development and Employment Department.',
        '6-month industry training period with direct benefit stipend transfer.',
        'Crucial for upcoming MPSC and Talathi government schemes syllabus section.',
      ],
      hi: [
        'महाराष्ट्र कौशल विकास विभाग द्वारा योजना का संचालन किया जा रहा है।',
        'युवाओं को 6 माह का प्रशिक्षण और प्रत्यक्ष बैंक ट्रांसफर द्वारा स्टाइपेंड मिलेगा।',
        'प्रतियोगी परीक्षाओं के लिए सरकारी योजनाओं के अंतर्गत अत्यंत महत्वपूर्ण।',
      ],
    },
    mcqQuestion: {
      question: 'महाराष्ट्र शासनाच्या "मुख्यमंत्री युवा कार्यप्रशिक्षण" योजनेअंतर्गत पदवीधर उमेदवारांना दरमहा किती विद्यावेतन दिले जाणार आहे?',
      options: ['₹६,०००', '₹८,०००', '₹१०,०००', '₹१२,०००'],
      answerIndex: 2,
      explanation: 'पदवीधर उमेदवारांसाठी दरमहा १०,००० रुपये, तर १२ वी उत्तीर्ण उमेदवारांसाठी ६,००० रुपये विद्यावेतन मंजूर आहे.',
    },
  },
  {
    id: 'ca-2',
    title: {
      mr: 'इस्रोची नवीन "चांद्रयान-४" नमुना परती मोहीम (Sample Return Mission) अंतिम टप्प्यात',
      en: 'ISRO Chandrayaan-4 Lunar Sample Return Mission Enters Final Configuration',
      hi: 'इसरो का "चंद्रयान-4" लूनर सैंपल रिटर्न मिशन अंतिम चरण में',
    },
    category: 'Science & Tech',
    date: '२० सप्टेंबर २०२६',
    summary: {
      mr: 'चंद्राच्या पृष्ठभागावरील माती व खडक पृथ्वीवर परत आणण्यासाठी भारताची ऐतिहासिक मोहीम मंजूर.',
      en: 'India’s space agency prepares landmark mission to bring lunar regolith samples back to Earth.',
      hi: 'चंद्रमा की सतह से नमूने पृथ्वी पर वापस लाने के लिए भारत के महत्वाकांक्षी अंतरिक्ष मिशन की तैयारी।',
    },
    points: {
      mr: [
        'केंद्रीय मंत्रिमंडळाने चांद्रयान-४ मोहिमेसाठी ₹२,१०४ कोटी रुपयांचा निधी मंजूर केला आहे.',
        'या मोहिमेत एकूण ५ मॉड्यूल्स असणार असून दोन वेगवेगळ्या रॉकेटद्वारे प्रक्षेपण केले जाईल.',
        'सायन्स आणि टेक्नॉलॉजी विभागात यावर थेट तांत्रिक प्रश्न विचारला जाऊ शकतो.',
      ],
      en: [
        'Union Cabinet approved ₹2,104 crore budget allocation for Chandrayaan-4.',
        'Features a modular 5-component stack utilizing dual launch architecture.',
        'High-probability question for MPSC Rajyaseva Science and Technology paper.',
      ],
      hi: [
        'केंद्रीय मंत्रिमंडल ने चंद्रयान-4 के लिए ₹2,104 करोड़ का बजट स्वीकृत किया।',
        'यह भारत का पहला सैंपल रिटर्न लूनर मिशन होगा।',
        'विज्ञान एवं प्रौद्योगिकी अनुभाग में सीधा प्रश्न संभावित।',
      ],
    },
    mcqQuestion: {
      question: 'चांद्रयान-४ मोहिमेचा मुख्य उद्देश काय आहे?',
      options: [
        'चंद्रावर मानवरहित प्रयोगशाळा स्थापन करणे',
        'चंद्रावरील मातीचे नमुने सुरक्षितपणे पृथ्वीवर परत आणणे',
        'चंद्राच्या कक्षेत कायमस्वरूपी स्पेस स्टेशन उभारणे',
        'सूर्याच्या सौर वादळांचा अभ्यास करणे',
      ],
      answerIndex: 1,
      explanation: 'चांद्रयान-४ ही एक "लूनर सॅम्पल रिटर्न मिशन" असून चंद्रावरून नमुने पृथ्वीवर आणणे हे तिचे प्रमुख उद्दिष्ट आहे.',
    },
  },
];

export const BLOG_POSTS_DATA: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'mpsc-prelims-last-30-days-revision-strategy',
    title: {
      mr: 'MPSC प्रिलिम्स शेवटचे ३० दिवस: रिव्हिजन कसे करावे आणि कट-ऑफ कसा पार पाडावा?',
      en: 'MPSC Prelims Last 30 Days: High-Yield Revision Blueprint & Cut-off Mastery',
      hi: 'MPSC प्रीलिम्स अंतिम 30 दिन: हाई-यील्ड रिवीजन रणनीति और कट-ऑफ पार करने के सूत्र',
    },
    excerpt: {
      mr: 'शेवटच्या एका महिन्यात नवीन पुस्तके वाचण्याऐवजी आधी केलेल्या अभ्यासाचे पक्के रिव्हिजन, PYQs सराव आणि वेळेचे नियोजन कसे करावे याविषयी सविस्तर मार्गदर्शन.',
      en: 'An actionable, data-driven checklist to optimize your final 30 days before MPSC Prelims without burning out.',
      hi: 'अंतिम एक महीने में नई किताबों के बजाय शॉर्ट नोट्स, PYQs अभ्यास और मॉक टेस्ट द्वारा रिवीजन की सर्वश्रेष्ठ रणनीति।',
    },
    content: {
      mr: 'स्पर्धा परीक्षेत यश मिळवणारे आणि अपयशी ठरणारे यांच्यात केवळ एकाच गोष्टीचा फरक असतो — तो म्हणजे शेवटच्या महिन्यातील रिव्हिजन! प्रिलिम्सच्या शेवटच्या ३० दिवसांत दररोज किमान ५० ते १०० PYQs सोडवणे, स्वतः तयार केलेल्या शॉर्ट नोट्सचे वाचन करणे आणि निगेटिव्ह मार्किंग टाळण्याची कला शिकणे अनिवार्य आहे.',
      en: 'The difference between clearing the cut-off and falling short often boils down to systematic revision during the last 30 days. Prioritize high-weightage topics: Constitutional articles, Maharashtra geography maps, modern reformers, and the last 6 months of current affairs.',
      hi: 'अंतिम 30 दिनों में समय प्रबंधन अत्यंत महत्वपूर्ण है। इतिहास, भूगोल, राज्यव्यवस्था के मुख्य विषयों का चार्ट आधारित रिवीजन करें और रोज कम से कम 100 बहुविकल्पीय प्रश्न हल करें।',
    },
    category: 'MPSC Preparation',
    author: {
      name: 'रोहित सावंत (उपजिल्हाधिकारी २०२४ बॅच)',
      role: 'Chai Revision मेंटॉर',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    },
    publishedDate: '१५ सप्टेंबर २०२६',
    readingTime: '६ मिनिटे वाचन',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    tableOfContents: [
      '१. ३० दिवसांचे आठवडावार रिव्हिजन वेळापत्रक',
      '२. विषयवार प्राधान्यक्रम (High-Yield Topics)',
      '३. मॉक टेस्ट्स सोडवताना होणाऱ्या ३ चुका',
      '४. CSAT क्वालिफाईंग पेपरची रणनीती',
      '५. परीक्षेच्या आदल्या दिवशीचे मानसिक संतुलन',
    ],
  },
  {
    id: 'blog-2',
    slug: 'talathi-exam-tcs-pattern-analysis',
    title: {
      mr: 'TCS पॅटर्न तलाठी परीक्षेत मराठी व इंग्रजी व्याकरणात पैकीच्या पैकी गुण कसे मिळवावेत?',
      en: 'How to Score 50/50 in Marathi & English Grammar under TCS Pattern',
      hi: 'TCS पैटर्न में मराठी एवं अंग्रेजी व्याकरण में पूरे अंक कैसे प्राप्त करें?',
    },
    excerpt: {
      mr: 'TCS ने मागील २ वर्षांत विचारलेल्या सर्व प्रश्नांचे वर्गीकरण आणि व्याकरणातील ट्रिकी प्रश्नांवर पकड मिळवण्याच्या सोप्या पद्धती.',
      en: 'Detailed linguistic breakdown of high-frequency question types in TCS and IBPS exams for state recruitment.',
      hi: 'TCS और IBPS पैटर्न में व्याकरण के सबसे अधिक पूछे जाने वाले विषयों का विश्लेषण और हल करने की ट्रिक्स।',
    },
    content: {
      mr: 'TCS पॅटर्ननुसार होणाऱ्या स्पर्धा परीक्षांमध्ये मराठी आणि इंग्रजी व्याकरण हे सर्वाधिक गुण मिळवून देणारे विषय ठरतात. प्रयोग, समास, विभक्ती, समानार्थी-विरुद्धार्थी शब्द आणि म्हणी यावर थेट प्रश्न विचारले जातात. दररोज २० मिनिटे शब्दसंग्रहाचे रिव्हिजन करणे आणि मागील प्रश्नपत्रिकांचा सराव करणे हाच यशाचा खरा मार्ग आहे.',
      en: 'In TCS and IBPS examinations, language comprehension and grammar sections carry high scoring potential. Mastering active-passive transformations, sentence rearrangement, vocabulary roots, and idiom comprehension directly increases your percentile. Consistent daily practice of mock questions ensures speed and accuracy.',
      hi: 'TCS पैटर्न की परीक्षाओं में व्याकरण स्कोरिंग विषय होता है। संधि, समास, काल, पर्यायवाची और विलोम शब्दों का नियमित अभ्यास करें। पिछले वर्षों के प्रश्नों का विश्लेषण करके कमजोर विषयों पर विशेष ध्यान दें।',
    },
    category: 'Exam Strategy',
    author: {
      name: 'प्रा. स्वाती कांबळे',
      role: 'भाषातज्ज्ञ व मार्गदर्शक',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    },
    publishedDate: '१० सप्टेंबर २०२६',
    readingTime: '५ मिनिटे वाचन',
    coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    tableOfContents: [
      '१. TCS पॅटर्न व्याकरणाची मूळ रचना',
      '२. प्रयोग व समास ओळखण्याच्या शॉर्टकट ट्रिक्स',
      '३. इंग्रजी व्होकॅब्युलरी कशी पाठ करावी?',
      '४. उतारा वाचन (Comprehension) अचूक सोडवण्याचे तंत्र',
    ],
  },
];
